// the class names used in the page object methods below are randomly generated by react and are not best practices to use as a way to locate elements in automation tests

class PageObjects {
  verifyCorrectAmountOfProductsAreVisible() {
    return cy
      .get('.sc-ebmerl-4')
      .invoke('text')
      .then((text) => {
        const productCount = Number(text.match(/\d+/)[0]);

        this.findProduct().should('have.length', productCount);
      });
  }

  findProduct() {
    return cy.get('.sc-124al1g-2');
  }

  findProductImage() {
    return cy.get('.sc-124al1g-1');
  }

  findProductTitle() {
    return cy.get('.sc-124al1g-4');
  }

  findProductPrice() {
    return cy.get('.sc-124al1g-6');
  }

  findFilterButton(availableSize: string) {
    return cy.get('.sc-bj2vay-1 label').filter((index, label) => {
      return label.textContent.trim() === availableSize;
    });
  }

  findAddToCartButton() {
    return cy.get('.sc-124al1g-0');
  }

  findProductTitleInCart() {
    return cy.get('.sc-11uohgb-2');
  }
}
export default PageObjects;
